### PR TITLE
Scala 2.11 2.12

### PR DESCRIPTION
**Pull request by gbicou**
Cross compilation to scala 2.11 and scala 2.12

### CODE REVIEW

**Comment by OmarAyo** [comment]
CLA received

**Comment by igreenfield** [comment]
What the status of that?

**Comment by f1yegor** [comment]
@bicouy0 could you resolve merge conflict? I'm interested in this change to be in trunk

**Comment by rashtao** [comment]
Fixed in https://github.com/arangodb/java-velocypack-module-scala/releases/tag/v1.2.0

**Pull request closed without merging**
