### PR TITLE
Add scala 2.13 support, prepare cross scala build and release using SBT

### PR DESCRIPTION
**Pull request by dacr**
Everything should be OK to cross publish (scala 2.12 & 2.13 artifacts) to maven central, check the `publish.sbt` configuration file. To cross publish to central just execute `sbt release` it will trigger all the process, even tagging and `version.sbt` file content update.

### CODE REVIEW

**Comment by dacr** [comment]
I've also added all the required changes linked to scala 2.13 refactored collections.

**Comment by rashtao** [comment]
@dacr thanks for contributing!
Due to the nature of this library, we decided to keep different branches for each different Scala version and avoid cross compilation to different versions. This approach requires a bit more work for merging code changes to all branches, but it is safer and easier to maintain with respect to differences in collection API across many Scala versions.

Furthermore, since we don't need cross compilation, I guess there is no need to switch to `sbt`. We would like to keep the current `mvn` approach since it is already integrated in our internal CI.

I have created a new branch named `release/velocypack-module-scala_2.12`, so now `master` can be updated to Scala `2.13`.

**Comment by rashtao** [comment]
@dacr 

We are obliged by law to have a signed scanned copy of a Contributor License Agreement (CLA) to be able to accept pull requests to the official ArangoDB repository - even for such small changes.

We use an Apache 2 CLA for ArangoDB and its companion projects, which can be found here: https://www.arangodb.com/documents/cla.pdf Just fill in the form, sign and send a scanned copy over to cla@arangodb.com

Thank you

**Comment by dacr** [comment]
> @dacr
> 
> We are obliged by law to have a signed scanned copy of a Contributor License Agreement (CLA) to be able to accept pull requests to the official ArangoDB repository - even for such small changes.
> 
> We use an Apache 2 CLA for ArangoDB and its companion projects, which can be found here: https://www.arangodb.com/documents/cla.pdf Just fill in the form, sign and send a scanned copy over to [cla@arangodb.com](mailto:cla@arangodb.com)
> 
> Thank you

Just signed today, sorry for the delay,
regards,
David.

**Review by rashtao — APPROVED** [review]
LGTM, thanks for contributing!

**Pull request merged**
